export interface IPurchasingHandler {
  register(request: any, reply: any): Promise<void>
  login(request: any, reply: any): Promise<void>
  changedPassword(request: any, reply: any): Promise<void>
  forgotPassword(request: any, reply: any): Promise<void>
  pengajuanPksCurah(request: any, reply: any): Promise<void>
  pengajuanFreight(request: any, reply: any): Promise<void>
  findAllPksCurah(request: any, reply: any): Promise<void>
  findAllPksCurahBank(request: any, reply: any): Promise<void>
  findBankByPksCurahId(request: any, reply: any): Promise<void>
  findOnePksCurah(request: any, reply: any): Promise<void>
  updatePksCurah(request: any, reply: any): Promise<void>
  deletePksCurah(request: any, reply: any): Promise<void>
  findAllFreight(request: any, reply: any): Promise<void>
  findOneFreight(request: any, reply: any): Promise<void>
  updateFreight(request: any, reply: any): Promise<void>
  deleteFreight(request: any, reply: any): Promise<void>
  findAllFreightBank(request: any, reply: any): Promise<void>
  findBankByFreightId(request: any, reply: any): Promise<void>
  findAllCurrency(request: any, reply: any): Promise<void>
  findOneCurrency(request: any, reply: any): Promise<void>
  findOneStockpile(request: any, reply: any): Promise<void>
  findAllStockpile(request: any, reply: any): Promise<void>
  pengajuanPkhoa(request: any, reply: any): Promise<void>
  findAllPkhoa(request: any, reply: any): Promise<void>
  findOnePkhoa(request: any, reply: any): Promise<void>
  updatePkhoa(request: any, reply: any): Promise<void>
  deletePkhoa(request: any, reply: any): Promise<void>
  findPkhoaExclude(request: any, reply: any): Promise<void>
  pengajuanKontrakPks(request: any, reply: any): Promise<void>
  findAllKontrakPks(request: any, reply: any): Promise<void>
  findOneKontrakPks(request: any, reply: any): Promise<void>
  findPlanPaymentDate(request: any, reply: any): Promise<void>
  deletePengajuanKontrakPks(request: any, reply: any): Promise<void>
  updateFilePurchasing(request: any, reply: any): Promise<void>
  updateTerminKontrakPks(request: any, reply: any): Promise<void>
  deleteTerminKontrakPks(request: any, reply: any): Promise<void>
}